//Bibliotecas
#Include "Protheus.ch"
 
/*/{Protheus.doc} zAltPar
Função que altera parâmetros do tipo Lógico (deve ser um parâmetro com conteúdo lógico na SX6, por exemplo, "MV_CHVNFE")
@author Atilio
@since 25/04/2017
@version 1.0
@type function
    @param cParametro, Character, Código do parâmetro que será atualizado
/*/


 
User Function zAltPar()
    Local aArea    := GetArea()
    Local cConsAtu := ""
    Local cConsNov := ""
    Local cOpcao   := ""
    Local aBotoes  := {}
    Local cMensag  := ""
    //Default cParametro := ""
    PRIVATE cParametro := "MV_CONSEST"

    //Se tiver parâmetro
    If !Empty(cParametro)
        lConsAtu := GetNewPar(cParametro, "S")
         
        //Adiciona os botões
        aAdd(aBotoes, Iif(cConsAtu,  "Manter Habilitado",   "Habilitar"))   //Opção 1
        aAdd(aBotoes, Iif(!cConsAtu, "Manter Desabilitado", "Desabilitar")) //Opção 2
        aAdd(aBotoes, "Cancelar")                                           //Opção 3
         
        //Mostra o aviso e pega o botão
        cMensag := "Atualmente o parâmetro esta " + Iif(lConsAtu, "HABILITADO", "DESABILITADO") + "." + CRLF
        cMensag += "Deseja alterar?"
        cOpcao := Aviso("Atenção", cMensag, aBotoes, 2)
         
        //Definindo a opção nova
        If nOpcao == "S"
            cConsNov := "S"
        ElseIf nOpcao == "N"
            cConsNov := "N"
        EndIf
         
        //Se não for nulo
        If cConsNov != Nil
            //Se o conteúdo novo for diferente do atual
            If cConsNov != lConsAtu
                PutMV(cParametro, cConsNov)
                 
                Final("Atenção", "A tela será fechada e deve ser aberta novamente!")
            EndIf
        EndIf
    EndIf
     
    RestArea(aArea)
Return
