//Bibliotecas
#Include "tlpp-core.th"
#Include "TOTVS.ch" //por causa da RGB()
#Include "TopConn.ch"
#Include "RPTDef.ch"
#Include "FWPrintSetup.ch"

//Declaração da namespace
Namespace custom.autumn.printer

//Constantes
#Define CRLF Chr(13) + Chr(10) //Carriage Return Line Feed

//Alinhamentos
#Define PAD_LEFT    0
#Define PAD_RIGHT   1
#Define PAD_CENTER  2
#Define PAD_JUSTIFY 3 //Opção disponível somente a partir da versão 1.6.2 da TOTVS Printer

//Cor(es)
Static nColorGray := RGB(110, 110, 110) As Numeric

/*/{Protheus.doc} ZRELCLI01
Relatorio Relacao da ultima compras de clientes
@author Fernando Jose Rodrigues
@since 01/02/2026
@version 1.0
@type User Function
@obs Codigo gerado automaticamente pelo Autumn Code Maker
@see http://autumncodemaker.com
@example custom.autumn.printer.u_ZRELCLI01()
/*/

User Function ZRELCLI01()
	Local aArea := FWGetArea() As Array
	Local aParameters   := {} As Array
	Local xPar0 := Space(12) As Character
	Local xPar1 := Space(12) As Character
	Local xPar2 := Space(6) As Character
	Local xPar3 := Space(6) As Character

	//Adicionando os parametros do ParamBox
	aAdd(aParameters, {1, "Cliente De:", xPar0,  "", ".T.", "SA1", ".T.", 80,  .F.})
	aAdd(aParameters, {1, "Cliente Até:", xPar1,  "", ".T.", "SA1", ".T.", 80,  .F.})
	aAdd(aParameters, {1, "Vendedor De:", xPar2,  "", ".T.", "SA3", ".T.", 80,  .F.})
	aAdd(aParameters, {1, "Vendedor Até", xPar3,  "", ".T.", "SA3", ".T.", 80,  .F.})

	//Se a pergunta for confirma, cria o relatorio
	If ParamBox(aParameters, 'Informe os parâmetros', /*aRet*/, /*bOk*/, /*aButtons*/, /*lCentered*/, /*nPosx*/, /*nPosy*/, /*oDlgWizard*/, /*cLoad*/, .F., .F.)
		Processa({|| createReport()})
	EndIf

	FWRestArea(aArea)
Return

/*/{Protheus.doc} createReport
Faz a impressão do relatório ZRELCLI01
@author Fernando Jose Rodrigues
@since 01/02/2026
@version 1.0
@type Static Function
@obs Codigo gerado automaticamente pelo Autumn Code Maker
@see http://autumncodemaker.com
/*/

Static Function createReport()
	Local aArea          := FWGetArea() As Array
	Local nTotal         := 0 As Numeric
	Local nCurrent       := 0 As Numeric
	Local cQuery         := '' As Character
	Local cFileName      := 'ZRELCLI01'+RetCodUsr()+'_' + dToS(Date()) + '_' + StrTran(Time(), ':', '-') + '.pdf' As Character
	Local cObservacao    := ""
	Private oPrintReport As Object
	Private cTimeReport    := Time() As Character
	Private nPageCurrent   := 1 As Numeric
	Private cCompanyLogo   := searchLogo() As Character
	//Linhas e colunas
	Private nReportLine    := 0 As Numeric
	Private nFooterLimit   := 800 As Numeric
	Private nLeftMargin    := 010 As Numeric
	Private nRightLimit    := 580 As Numeric
	Private nMiddleCol   := (nRightLimit - nLeftMargin) / 2 As Numeric
	//Colunas dos relatorio
	Private nColCod      := nLeftMargin As Numeric
	Private nColNome     := nLeftMargin + 65 As Numeric
	Private nColUlt      := nLeftMargin + 250 As Numeric
	Private nColObs      := nLeftMargin + 330 As Numeric
	// Private nColData5    := nLeftMargin + 155 As Numeric
	//Declarando as fontes
	Private cFont                := 'Arial' As Character
	Private oFontDetails         := TFont():New(cFont, /*uPar2*/, -11, /*uPar4*/, .F., /*uPar6*/, /*uPar7*/, /*uPar8*/, /*uPar9*/, .F.) As Object
	Private oFontDetailsBold     := TFont():New(cFont, /*uPar2*/, -13, /*uPar4*/, .T., /*uPar6*/, /*uPar7*/, /*uPar8*/, /*uPar9*/, .F.) As Object
	Private oFontFooter          := TFont():New(cFont, /*uPar2*/, -8,  /*uPar4*/, .F., /*uPar6*/, /*uPar7*/, /*uPar8*/, /*uPar9*/, .F.) As Object
	Private oFontHeaderColumns   := TFont():New(cFont, /*uPar2*/, -7,  /*uPar4*/, .F., /*uPar6*/, /*uPar7*/, /*uPar8*/, /*uPar9*/, .F.) As Object
	Private oFontTitle           := TFont():New(cFont, /*uPar2*/, -15, /*uPar4*/, .T., /*uPar6*/, /*uPar7*/, /*uPar8*/, /*uPar9*/, .F.) As Object

	//Monta a consulta de dados
	cQuery += "SELECT A1_COD, A1_NOME, A1_ULTCOM, SA1.R_E_C_N_O_ AS RECNUM FROM SA1990 SA1 "		+ CRLF
	cQuery += " "		+ CRLF
	cQuery += "WHERE "		+ CRLF
	cQuery += " A1_FILIAL = '' "		+ CRLF
	cQuery += " AND A1_COD >= '" + MV_PAR01 + "' " + CRLF
	cQuery += " AND A1_COD <= '" + MV_PAR02 + "' " + CRLF
	cQuery += " AND A1_VEND >= '" + MV_PAR03 + "' "	+ CRLF
	cQuery += " AND A1_VEND <= '" + MV_PAR04 + "' "	+ CRLF
	cQuery += " AND A1_MSBLQL != '1' "		+ CRLF
	cQuery += " AND SA1.D_E_L_E_T_ = '' "		+ CRLF
	cQuery += "ORDER BY A1_COD"		+ CRLF
	If '--' $ cQuery .Or. 'WITH' $ Upper(cQuery) .Or. 'NOLOCK' $ Upper(cQuery)
		FWAlertInfo('Alguns comandos (como --, WITH e NOLOCK), não são executados pela PLSQuery devido ao ChangeQuery. Tente migrar da PLSQuery para TCQuery.', 'Atenção')
	EndIf
	PLSQuery(cQuery, 'QRY_AUX')

	//Define o tamanho da régua
	DbSelectArea('QRY_AUX')
	QRY_AUX->(DbGoTop())
	Count to nTotal
	ProcRegua(nTotal)
	QRY_AUX->(DbGoTop())

	//Somente se tiver dados
	If ! QRY_AUX->(EoF())
		//Criando o objeto de impressao
		oPrintReport := FWMSPrinter():New(;
			cFileName,;      // cFilePrinter
		IMP_PDF,;        // nDevice
		.F.,;            // lAdjustToLegacy
		,;               // cPathInServer
		.T.,;            // lDisabeSetup
		,;               // lTReport
		@oPrintReport,;  // oPrintSetup
		,;               // cPrinter
		,;               // lServer
		,;               // lParam10
		,;               // lRaw
		.T.;             // lViewPDF
		)
		oPrintReport:cPathPDF := GetTempPath()
		oPrintReport:SetResolution(72)
		oPrintReport:SetPortrait()
		oPrintReport:SetPaperSize(DMPAPER_A4)
		oPrintReport:SetMargin(0, 0, 0, 0)

		//Imprime os dados
		printHeader()
		While ! QRY_AUX->(EoF())
			nCurrent++
			IncProc('Imprimindo registro ' + cValToChar(nCurrent) + ' de ' + cValToChar(nTotal) + '...')

			//Se atingiu o limite, quebra de pagina
			validPageBreak()

			SA1->(dbGoTo(QRY_AUX->RECNUM))
			If ! Empty(SA1->A1_X_RELAT)
				cObservacao := Formula(SA1->A1_X_RELAT)
			Else
				cObservacao := ""
			EndIf

			//Imprime a linha atual
			oPrintReport:SayAlign(nReportLine, nColCod, Alltrim(Transform(QRY_AUX->A1_COD, '@!' )), oFontDetails, 60, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
			oPrintReport:SayAlign(nReportLine, nColNome, Alltrim(Transform(QRY_AUX->A1_NOME, '@1' )), oFontDetails, 150, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
			oPrintReport:SayAlign(nReportLine, nColUlt, dToC(QRY_AUX->A1_ULTCOM), oFontDetails, 80, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
			oPrintReport:SayAlign(nReportLine, nColObs, Alltrim(cObservacao), oFontDetails, 300, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)

			nReportLine += 15
			oPrintReport:Line(nReportLine-3, nLeftMargin, nReportLine-3, nRightLimit, nColorGray)

			//Se atingiu o limite, quebra de pagina
			validPageBreak()

			QRY_AUX->(DbSkip())
		EndDo

		//Imprime o último rodapé
		printFooter()

		oPrintReport:Preview()
	Else
		FWAlertError('Não foi encontrado informações com os parâmetros informados!', 'Atenção')
	EndIf
	QRY_AUX->(DbCloseArea())

	FWRestArea(aArea)
Return

/*/{Protheus.doc} searchLogo
Função que retorna o logo da empresa conforme configuração da DANFE
@author Fernando Jose Rodrigues
@since 01/02/2026
@version 1.0
@type Static Function
@obs Codigo gerado automaticamente pelo Autumn Code Maker
@see http://autumncodemaker.com
/*/

Static Function searchLogo()
	Local cLogo       := '\system\lgrl99.bmp' As Character
Return cLogo

/*/{Protheus.doc} printHeader
Função que imprime o cabeçalho do relatório
@author Fernando Jose Rodrigues
@since 01/02/2026
@version 1.0
@type Static Function
@obs Codigo gerado automaticamente pelo Autumn Code Maker
@see http://autumncodemaker.com
/*/

Static Function printHeader()
	Local cText        := '' As Character
	Local nHeaderLine  := 015 As Numeric

	//Iniciando Pagina
	oPrintReport:StartPage()

	//Imprime o logo
	If File(cCompanyLogo)
		oPrintReport:SayBitmap(005, nLeftMargin, cCompanyLogo, 030, 030)
	EndIf

	//Cabecalho
	cText := 'Listagem de clientes'
	oPrintReport:SayAlign(nHeaderLine, nMiddleCol-200, cText, oFontTitle, 400, 20, /*nClrText*/, PAD_CENTER, /*nAlignVert*/)

	//Linha Separatoria
	nHeaderLine += 020
	oPrintReport:Line(nHeaderLine,   nLeftMargin, nHeaderLine,   nRightLimit)

	//Atualizando a linha inicial do relatorio
	nReportLine := nHeaderLine + 5

	If nPageCurrent == 1
		//Imprimindo os parâmetros
		cText := MV_PAR01
		oPrintReport:SayAlign(nReportLine, nLeftMargin, 'Cliente De:', oFontDetailsBold, 200, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
		oPrintReport:SayAlign(nReportLine, nLeftMargin+200, cText, oFontDetails, 200, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
		nReportLine += 15

		cText := MV_PAR02
		oPrintReport:SayAlign(nReportLine, nLeftMargin, 'Cliente Até:', oFontDetailsBold, 200, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
		oPrintReport:SayAlign(nReportLine, nLeftMargin+200, cText, oFontDetails, 200, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
		nReportLine += 15

		cText := MV_PAR03
		oPrintReport:SayAlign(nReportLine, nLeftMargin, 'Vendedor De:', oFontDetailsBold, 200, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
		oPrintReport:SayAlign(nReportLine, nLeftMargin+200, cText, oFontDetails, 200, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
		nReportLine += 15

		cText := MV_PAR04
		oPrintReport:SayAlign(nReportLine, nLeftMargin, 'Vendedor Até', oFontDetailsBold, 200, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
		oPrintReport:SayAlign(nReportLine, nLeftMargin+200, cText, oFontDetails, 200, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
		nReportLine += 15

		oPrintReport:Line(nReportLine-3, nLeftMargin, nReportLine-3, nRightLimit, nColorGray)
		nReportLine += 5
	EndIf

	oPrintReport:SayAlign(nReportLine, nColCod, 'Código', oFontHeaderColumns, 60, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
	oPrintReport:SayAlign(nReportLine, nColNome, 'Cliente', oFontHeaderColumns, 150, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
	oPrintReport:SayAlign(nReportLine, nColUlt, 'Data Ultima Compra', oFontHeaderColumns, 80, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
	oPrintReport:SayAlign(nReportLine, nColObs, 'Observacao', oFontHeaderColumns, 300, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)
	nReportLine += 15
Return

/*/{Protheus.doc} printFooter
Função que imprime o rodapé e encerra a página
@author Fernando Jose Rodrigues
@since 01/02/2026
@version 1.0
@type Static Function
@obs Codigo gerado automaticamente pelo Autumn Code Maker
@see http://autumncodemaker.com
/*/

Static Function printFooter()
	Local nFooterLine := nFooterLimit As Numeric
	Local cText       := '' As Character

	//Linha Separatoria
	oPrintReport:Line(nFooterLine,   nLeftMargin, nFooterLine,   nRightLimit)
	nFooterLine += 3

	//Dados da Esquerda
	cText := dToC(dDataBase) + '     ' + cTimeReport + '     ' + FunName() + ' (ZRELCLI01)     ' + UsrRetName(RetCodUsr())
	oPrintReport:SayAlign(nFooterLine, nLeftMargin, cText, oFontFooter, 500, 10, /*nClrText*/, PAD_LEFT, /*nAlignVert*/)

	//Direita
	cText := 'Pagina '+cValToChar(nPageCurrent)
	oPrintReport:SayAlign(nFooterLine, nRightLimit-40, cText, oFontFooter, 040, 10, /*nClrText*/, PAD_RIGHT, /*nAlignVert*/)

	//Finalizando a pagina e somando mais um
	oPrintReport:EndPage()
	nPageCurrent++
Return

/*/{Protheus.doc} validPageBreak
Função que valida se a linha esta próxima do final, se sim quebra a página
@author Fernando Jose Rodrigues
@since 01/02/2026
@version 1.0
@type Static Function
@obs Codigo gerado automaticamente pelo Autumn Code Maker
@see http://autumncodemaker.com
/*/

Static Function validPageBreak()
	If nReportLine >= nFooterLimit - 10
		printFooter()
		printHeader()
	EndIf
Return
